org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.parallel=true
org.gradle.caching=true

BASE_URL=https://mcmoddev.ru
APP_ID=86

appArtifactId=tnt
appVersionCode=1
appVersionName=1.0
metricaApiKey=3a353876-c4d7-40f1-93cf-80e3ef0cf5e7