org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.parallel=true
org.gradle.caching=true

BASE_URL=https://mcmoddev.ru
APP_ID=87

appArtifactId=cavedweller
appVersionCode=1
appVersionName=1.0
metricaApiKey=83ee082f-1d5c-4ec4-ba2e-6efdab3e38ab